# https://docs.travis-ci.com/user/languages/go/
language: go
go: 
- 1.10.x
- 1.11.x
- tip

install: true

script:
- go test -v ./rosalind/...
- go test -v ./chapter1/...
- go test -v ./chapter2/...
- go test -v ./chapter3/...
